# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build Projects

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:

  build-hello-world:
    runs-on: ubuntu-latest
    name: Build Hello World

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: 🔧 Configure CMake
      run: cmake -B ${{github.workspace}}/build -S${{github.workspace}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: 🔨 Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
